# Generated by Django 3.2 on 2021-04-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210423_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_string',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
