# Generated by Django 3.2 on 2021-04-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_date_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriescases',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_cases', to='api.report'),
        ),
        migrations.AlterField(
            model_name='timeseriescasesregional',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_regional', to='api.report'),
        ),
        migrations.AlterField(
            model_name='timeseriesvaccination',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_vaccination', to='api.report'),
        ),
    ]
