# Generated by Django 3.2 on 2021-04-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210425_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriescases',
            name='total_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeseriescases',
            name='total_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
