# Generated by Django 3.2 on 2021-04-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210426_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(default=0)),
                ('b1351', models.IntegerField(default=0)),
                ('b117', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.report')),
            ],
        ),
    ]
