# Generated by Django 3.2 on 2021-04-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_timeseriesvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='new_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='new_vaccinations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='num_fully_vaccinated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='num_part_vaccinated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='variant_b117',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='variant_b1351',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='variant_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TimeseriesVariant',
        ),
    ]
