# Generated by Django 3.2 on 2021-04-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210426_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicHealthUnit',
        ),
        migrations.RemoveField(
            model_name='timeseriescasesregional',
            name='report',
        ),
        migrations.RemoveField(
            model_name='timeseriesvaccination',
            name='report',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='variant_b117',
            new_name='total_variant_b117',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='variant_b1351',
            new_name='total_variant_b1351',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='variant_p1',
            new_name='total_variant_p1',
        ),
        migrations.DeleteModel(
            name='TimeseriesCases',
        ),
        migrations.DeleteModel(
            name='TimeseriesCasesRegional',
        ),
        migrations.DeleteModel(
            name='TimeseriesVaccination',
        ),
    ]
