# Generated by Django 3.2 on 2021-04-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_report_test_positivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_string', models.CharField(max_length=10)),
                ('Algoma_Public_Health_Unit', models.IntegerField(default=0)),
                ('Brant_County_Health_Unit', models.IntegerField(default=0)),
                ('Chatham_Kent_Health_Unit', models.IntegerField(default=0)),
                ('Durham_Region_Health_Department', models.IntegerField(default=0)),
                ('Eastern_Ontario_Health_Unit', models.IntegerField(default=0)),
                ('Grey_Bruce_Health_Unit', models.IntegerField(default=0)),
                ('Haldimand_Norfolk_Health_Unit', models.IntegerField(default=0)),
                ('Haliburton_Kawartha_Pine_Ridge_District_Health_Unit', models.IntegerField(default=0)),
                ('Halton_Region_Health_Department', models.IntegerField(default=0)),
                ('Hamilton_Public_Health_Services', models.IntegerField(default=0)),
                ('Hastings_and_Prince_Edward_Counties_Health_Unit', models.IntegerField(default=0)),
                ('Huron_Perth_District_Health_Unit', models.IntegerField(default=0)),
                ('Kingston_Frontenac_and_Lennox_and_Addington_Public_Health', models.IntegerField(default=0)),
                ('Lambton_Public_Health', models.IntegerField(default=0)),
                ('Leeds_Grenville_and_Lanark_District_Health_Unit', models.IntegerField(default=0)),
                ('Middlesex_London_Health_Unit', models.IntegerField(default=0)),
                ('Niagara_Region_Public_Health_Department', models.IntegerField(default=0)),
                ('North_Bay_Parry_Sound_District_Health_Unit', models.IntegerField(default=0)),
                ('Northwestern_Health_Unit', models.IntegerField(default=0)),
                ('Ottawa_Public_Health', models.IntegerField(default=0)),
                ('Peel_Public_Health', models.IntegerField(default=0)),
                ('Peterborough_Public_Health', models.IntegerField(default=0)),
                ('Porcupine_Health_Unit', models.IntegerField(default=0)),
                ('Region_of_WaterlooPublic_Health', models.IntegerField(default=0)),
                ('Renfrew_County_and_District_Health_Unit', models.IntegerField(default=0)),
                ('Simcoe_Muskoka_District_Health_Unit', models.IntegerField(default=0)),
                ('Southwestern_Public_Health', models.IntegerField(default=0)),
                ('Sudbury_and_District_Health_Unit', models.IntegerField(default=0)),
                ('Thunder_Bay_District_Health_Unit', models.IntegerField(default=0)),
                ('Timiskaming_Health_Unit', models.IntegerField(default=0)),
                ('Toronto_Public_Health', models.IntegerField(default=0)),
                ('Wellington_Dufferin_Guelph_Public_Health', models.IntegerField(default=0)),
                ('Windsor_Essex_County_Health_Unit', models.IntegerField(default=0)),
                ('York_Region_Public_Health_Services', models.IntegerField(default=0)),
            ],
        ),
    ]
